<?

function timezone_is_dst ($time, $id) {
 $tz = getenv("TZ");

 putenv("TZ=".$id);
 $lt = localtime($time, true);
 putenv("TZ=".$tz);
 return $lt['tm_isdst'];
}

function timezone_get_zone ($time, $id) {
 global $timezone_places;
 if (timezone_is_dst ($time, $id)
  return $timezone_places[$id]["dstid"];
 return $timezone_places[$id]["id"];
}

//$time should be a time in $zn, and will be normalised to GMT
function timezone_normalise ($time, $zn) {

}

//$Time should be GMT based time.
function timezone_ftime ($Time, $Format = TIME_MEDIUM, $zn) {
 global $timezone_zones;
 $time = itime ($time);
 $zone = $timezone_zones[$zn];
 
 if ($Format == TIME_TINY)
  return gmdate ("j/n", $Time + $zone["offset"]) . " " . $zn;
 else if ($Format == TIME_SHORT)
  return gmdate ("j/n G:ia", $Time) . " " . $zn;
 else if ($Format == TIME_LONG)
  return gmdate ("l jS of F Y h:i:s A", $Time) . " " . $zn;
// else if ($Format == TIME_SQL)
//  return gmdate ("YmdHis", $Time);
 else //if ($Format == TIME_MEDIUM)
  return gmdate("F j, Y, g:i a", $Time) . " " . $zn;
}

global $timezone_zones;
$timezones = array (
"GMT-1200" => array ("offset" => "-43200", "name" => "GMT-12:00"),
"GMT-1100" => array ("offset" => "-39600", "name" => "GMT-11:00"),
"WST" => array ("offset" => "28800", "name" => "Western Standard Time (Australia)"),
"SST" => array ("offset" => "-39600", "name" => "Samoa Standard Time"),
"NUT" => array ("offset" => "-39600", "name" => "Niue Time"),
"HAST" => array ("offset" => "-36000", "name" => "Hawaii-Aleutian Standard Time"),
"GMT-1000" => array ("offset" => "-36000", "name" => "GMT-10:00"),
"HST" => array ("offset" => "-36000", "name" => "Hawaii Standard Time"),
"TKT" => array ("offset" => "-36000", "name" => "Tokelau Time"),
"CKT" => array ("offset" => "-36000", "name" => "Cook Is. Time"),
"TAHT" => array ("offset" => "-36000", "name" => "Tahiti Time"),
"MART" => array ("offset" => "-34200", "name" => "Marquesas Time"),
"AKST" => array ("offset" => "-32400", "name" => "Alaska Standard Time"),
"GMT-0900" => array ("offset" => "-32400", "name" => "GMT-09:00"),
"GAMT" => array ("offset" => "-32400", "name" => "Gambier Time"),
"PST" => array ("offset" => "-28800", "name" => "Pacific Standard Time"),
"GMT-0800" => array ("offset" => "-28800", "name" => "GMT-08:00"),
"MST" => array ("offset" => "-25200", "name" => "Mountain Standard Time"),
"GMT-0700" => array ("offset" => "-25200", "name" => "GMT-07:00"),
"CST" => array ("offset" => "34200", "name" => "Central Standard Time (South Australia/New South Wales)"),
"EST" => array ("offset" => "36000", "name" => "Eastern Standard Time (Victoria)"),
"EAST" => array ("offset" => "-21600", "name" => "Easter Is. Time"),
"GMT-0600" => array ("offset" => "-21600", "name" => "GMT-06:00"),
"GALT" => array ("offset" => "-21600", "name" => "Galapagos Time"),
"COT" => array ("offset" => "-18000", "name" => "Colombia Time"),
"ACT" => array ("offset" => "-18000", "name" => "Acre Time"),
"ECT" => array ("offset" => "-18000", "name" => "Ecuador Time"),
"PET" => array ("offset" => "-18000", "name" => "Peru Time"),
"GMT-0500" => array ("offset" => "-18000", "name" => "GMT-05:00"),
"AST" => array ("offset" => "10800", "name" => "Arabia Standard Time"),
"PYT" => array ("offset" => "-14400", "name" => "Paraguay Time"),
"AMT" => array ("offset" => "14400", "name" => "Armenia Time"),
"VET" => array ("offset" => "-14400", "name" => "Venezuela Time"),
"GYT" => array ("offset" => "-14400", "name" => "Guyana Time"),
"BOT" => array ("offset" => "-14400", "name" => "Bolivia Time"),
"CLT" => array ("offset" => "-14400", "name" => "Chile Time"),
"FKT" => array ("offset" => "-14400", "name" => "Falkland Is. Time"),
"GMT-0400" => array ("offset" => "-14400", "name" => "GMT-04:00"),
"NST" => array ("offset" => "-12600", "name" => "Newfoundland Standard Time"),
"ART" => array ("offset" => "-10800", "name" => "Argentine Time"),
"BRT" => array ("offset" => "-10800", "name" => "Brazil Time"),
"GFT" => array ("offset" => "-10800", "name" => "French Guiana Time"),
"WGT" => array ("offset" => "-10800", "name" => "Western Greenland Time"),
"PMST" => array ("offset" => "-10800", "name" => "Pierre & Miquelon Standard Time"),
"UYT" => array ("offset" => "-10800", "name" => "Uruguay Time"),
"SRT" => array ("offset" => "-10800", "name" => "Suriname Time"),
"GMT-0300" => array ("offset" => "-10800", "name" => "GMT-03:00"),
"FNT" => array ("offset" => "-7200", "name" => "Fernando de Noronha Time"),
"GST" => array ("offset" => "14400", "name" => "Gulf Standard Time"),
"GMT-0200" => array ("offset" => "-7200", "name" => "GMT-02:00"),
"EGT" => array ("offset" => "3600", "name" => "Eastern Greenland Time"),
"AZOT" => array ("offset" => "-3600", "name" => "Azores Time"),
"CVT" => array ("offset" => "-3600", "name" => "Cape Verde Time"),
"GMT-0100" => array ("offset" => "-3600", "name" => "GMT-01:00"),
"GMT" => array ("offset" => "0", "name" => "Greenwich Mean Time"),
"WET" => array ("offset" => "0", "name" => "Western European Time"),
"GMT+0000" => array ("offset" => "0", "name" => "GMT+00:00"),
"UTC" => array ("offset" => "0", "name" => "Coordinated Universal Time"),
"CET" => array ("offset" => "3600", "name" => "Central European Time"),
"WAT" => array ("offset" => "3600", "name" => "Western African Time"),
"GMT+0100" => array ("offset" => "3600", "name" => "GMT+01:00"),
"MET" => array ("offset" => "3600", "name" => "Middle Europe Time"),
"EET" => array ("offset" => "7200", "name" => "Eastern European Time"),
"CAT" => array ("offset" => "7200", "name" => "Central African Time"),
"SAST" => array ("offset" => "7200", "name" => "South Africa Standard Time"),
"IST" => array ("offset" => "19800", "name" => "India Standard Time"),
"GMT+0200" => array ("offset" => "7200", "name" => "GMT+02:00"),
"EAT" => array ("offset" => "10800", "name" => "Eastern African Time"),
"SYOT" => array ("offset" => "10800", "name" => "Syowa Time"),
"GMT+0300" => array ("offset" => "10800", "name" => "GMT+03:00"),
"MSK" => array ("offset" => "10800", "name" => "Moscow Standard Time"),
"GMT+03:07" => array ("offset" => "11224", "name" => "GMT+03:07"),
"IRT" => array ("offset" => "12600", "name" => "Iran Time"),
"AQTT" => array ("offset" => "18000", "name" => "Aqtobe Time"),
"AZT" => array ("offset" => "14400", "name" => "Azerbaijan Time"),
"GET" => array ("offset" => "14400", "name" => "Georgia Time"),
"GMT+0400" => array ("offset" => "14400", "name" => "GMT+04:00"),
"SAMT" => array ("offset" => "14400", "name" => "Samara Time"),
"SCT" => array ("offset" => "14400", "name" => "Seychelles Time"),
"MUT" => array ("offset" => "14400", "name" => "Mauritius Time"),
"RET" => array ("offset" => "14400", "name" => "Reunion Time"),
"AFT" => array ("offset" => "16200", "name" => "Afghanistan Time"),
"TMT" => array ("offset" => "18000", "name" => "Turkmenistan Time"),
"KGT" => array ("offset" => "18000", "name" => "Kirgizstan Time"),
"TJT" => array ("offset" => "18000", "name" => "Tajikistan Time"),
"PKT" => array ("offset" => "18000", "name" => "Pakistan Time"),
"UZT" => array ("offset" => "18000", "name" => "Uzbekistan Time"),
"YEKT" => array ("offset" => "18000", "name" => "Yekaterinburg Time"),
"GMT+0500" => array ("offset" => "18000", "name" => "GMT+05:00"),
"TFT" => array ("offset" => "18000", "name" => "French Southern & Antarctic Lands Time"),
"MVT" => array ("offset" => "18000", "name" => "Maldives Time"),
"NPT" => array ("offset" => "20700", "name" => "Nepal Time"),
"MAWT" => array ("offset" => "21600", "name" => "Mawson Time"),
"VOST" => array ("offset" => "21600", "name" => "Vostok time"),
"ALMT" => array ("offset" => "21600", "name" => "Alma-Ata Time"),
"LKT" => array ("offset" => "21600", "name" => "Sri Lanka Time"),
"BDT" => array ("offset" => "21600", "name" => "Bangladesh Time"),
"NOVT" => array ("offset" => "21600", "name" => "Novosibirsk Time"),
"OMST" => array ("offset" => "21600", "name" => "Omsk Time"),
"BTT" => array ("offset" => "21600", "name" => "Bhutan Time"),
"GMT+0600" => array ("offset" => "21600", "name" => "GMT+06:00"),
"IOT" => array ("offset" => "21600", "name" => "Indian Ocean Territory Time"),
"MMT" => array ("offset" => "23400", "name" => "Myanmar Time"),
"CCT" => array ("offset" => "23400", "name" => "Cocos Islands Time"),
"DAVT" => array ("offset" => "25200", "name" => "Davis Time"),
"ICT" => array ("offset" => "25200", "name" => "Indochina Time"),
"HOVT" => array ("offset" => "25200", "name" => "Hovd Time"),
"WIT" => array ("offset" => "25200", "name" => "West Indonesia Time"),
"KRAT" => array ("offset" => "25200", "name" => "Krasnoyarsk Time"),
"GMT+0700" => array ("offset" => "25200", "name" => "GMT+07:00"),
"CXT" => array ("offset" => "25200", "name" => "Christmas Island Time"),
"BNT" => array ("offset" => "28800", "name" => "Brunei Time"),
"HKT" => array ("offset" => "28800", "name" => "Hong Kong Time"),
"IRKT" => array ("offset" => "28800", "name" => "Irkutsk Time"),
"MYT" => array ("offset" => "28800", "name" => "Malaysia Time"),
"PHT" => array ("offset" => "28800", "name" => "Philippines Time"),
"SGT" => array ("offset" => "28800", "name" => "Singapore Time"),
"CIT" => array ("offset" => "28800", "name" => "Central Indonesia Time"),
"ULAT" => array ("offset" => "28800", "name" => "Ulaanbaatar Time"),
"GMT+0800" => array ("offset" => "28800", "name" => "GMT+08:00"),
"CHOT" => array ("offset" => "32400", "name" => "Choibalsan Time"),
"TPT" => array ("offset" => "32400", "name" => "East Timor Time"),
"EIT" => array ("offset" => "32400", "name" => "East Indonesia Time"),
"KST" => array ("offset" => "32400", "name" => "Korea Standard Time"),
"JST" => array ("offset" => "32400", "name" => "Japan Standard Time"),
"YAKT" => array ("offset" => "32400", "name" => "Yakutsk Time"),
"GMT+0900" => array ("offset" => "32400", "name" => "GMT+09:00"),
"PWT" => array ("offset" => "32400", "name" => "Palau Time"),
"DDUT" => array ("offset" => "36000", "name" => "Dumont-d'Urville Time"),
"SAKT" => array ("offset" => "36000", "name" => "Sakhalin Time"),
"VLAT" => array ("offset" => "36000", "name" => "Vladivostok Time"),
"GMT+1000" => array ("offset" => "36000", "name" => "GMT+10:00"),
"ChST" => array ("offset" => "36000", "name" => "Chamorro Standard Time"),
"PGT" => array ("offset" => "36000", "name" => "Papua New Guinea Time"),
"TRUT" => array ("offset" => "36000", "name" => "Truk Time"),
"YAPT" => array ("offset" => "36000", "name" => "Yap Time"),
"LHST" => array ("offset" => "37800", "name" => "Load Howe Standard Time"),
"MAGT" => array ("offset" => "39600", "name" => "Magadan Time"),
"GMT+1100" => array ("offset" => "39600", "name" => "GMT+11:00"),
"VUT" => array ("offset" => "39600", "name" => "Vanuatu Time"),
"SBT" => array ("offset" => "39600", "name" => "Solomon Is. Time"),
"KOST" => array ("offset" => "39600", "name" => "Kosrae Time"),
"NCT" => array ("offset" => "39600", "name" => "New Caledonia Time"),
"PONT" => array ("offset" => "39600", "name" => "Ponape Time"),
"NFT" => array ("offset" => "41400", "name" => "Norfolk Time"),
"NZST" => array ("offset" => "43200", "name" => "New Zealand Standard Time"),
"ANAT" => array ("offset" => "43200", "name" => "Anadyr Time"),
"PETT" => array ("offset" => "43200", "name" => "Petropavlovsk-Kamchatski Time"),
"GMT+1200" => array ("offset" => "43200", "name" => "GMT+12:00"),
"MHT" => array ("offset" => "43200", "name" => "Marshall Islands Time"),
"FJT" => array ("offset" => "43200", "name" => "Fiji Time"),
"TVT" => array ("offset" => "43200", "name" => "Tuvalu Time"),
"NRT" => array ("offset" => "43200", "name" => "Nauru Time"),
"GILT" => array ("offset" => "43200", "name" => "Gilbert Is. Time"),
"WAKT" => array ("offset" => "43200", "name" => "Wake Time"),
"WFT" => array ("offset" => "43200", "name" => "Wallis & Futuna Time"),
"CHAST" => array ("offset" => "45900", "name" => "Chatham Standard Time"),
"GMT+1300" => array ("offset" => "46800", "name" => "GMT+13:00"),
"PHOT" => array ("offset" => "46800", "name" => "Phoenix Is. Time"),
"TOT" => array ("offset" => "46800", "name" => "Tonga Time"),
"GMT+1400" => array ("offset" => "50400", "name" => "GMT+14:00"),
"LINT" => array ("offset" => "50400", "name" => "Line Is. Time")
);

global $timezone_places;
$timezone_places = array (
"Etc/GMT-12" => array ("id" => "GMT-1200"),
"Etc/GMT-11" => array ("id" => "GMT-1100"),
"MIT" => array ("id" => "WST"),
"Pacific/Apia" => array ("id" => "WST"),
"Pacific/Midway" => array ("id" => "SST"),
"Pacific/Niue" => array ("id" => "NUT"),
"Pacific/Pago_Pago" => array ("id" => "SST"),
"Pacific/Samoa" => array ("id" => "SST"),
"US/Samoa" => array ("id" => "SST"),
"America/Adak" => array ("id" => "HAST", "dstid" => "HADT"),
"America/Atka" => array ("id" => "HAST", "dstid" => "HADT"),
"Etc/GMT-10" => array ("id" => "GMT-1000"),
"HST" => array ("id" => "HST"),
"Pacific/Fakaofo" => array ("id" => "TKT"),
"Pacific/Honolulu" => array ("id" => "HST"),
"Pacific/Johnston" => array ("id" => "HST"),
"Pacific/Rarotonga" => array ("id" => "CKT"),
"Pacific/Tahiti" => array ("id" => "TAHT"),
"SystemV/HST10" => array ("id" => "HST"),
"US/Aleutian" => array ("id" => "HAST", "dstid" => "HADT"),
"US/Hawaii" => array ("id" => "HST"),
"Pacific/Marquesas" => array ("id" => "MART"),
"AST" => array ("id" => "AKST", "dstid" => "AKDT"),
"America/Anchorage" => array ("id" => "AKST", "dstid" => "AKDT"),
"America/Juneau" => array ("id" => "AKST", "dstid" => "AKDT"),
"America/Nome" => array ("id" => "AKST", "dstid" => "AKDT"),
"America/Yakutat" => array ("id" => "AKST", "dstid" => "AKDT"),
"Etc/GMT-9" => array ("id" => "GMT-0900"),
"Pacific/Gambier" => array ("id" => "GAMT"),
"SystemV/YST9" => array ("id" => "GAMT"),
"SystemV/YST9YDT" => array ("id" => "AKST", "dstid" => "AKDT"),
"US/Alaska" => array ("id" => "AKST", "dstid" => "AKDT"),
"America/Dawson" => array ("id" => "PST", "dstid" => "PDT"),
"America/Ensenada" => array ("id" => "PST", "dstid" => "PDT"),
"America/Los_Angeles" => array ("id" => "PST", "dstid" => "PDT"),
"America/Tijuana" => array ("id" => "PST", "dstid" => "PDT"),
"America/Vancouver" => array ("id" => "PST", "dstid" => "PDT"),
"America/Whitehorse" => array ("id" => "PST", "dstid" => "PDT"),
"Canada/Pacific" => array ("id" => "PST", "dstid" => "PDT"),
"Canada/Yukon" => array ("id" => "PST", "dstid" => "PDT"),
"Etc/GMT-8" => array ("id" => "GMT-0800"),
"Mexico/BajaNorte" => array ("id" => "PST", "dstid" => "PDT"),
"PST" => array ("id" => "PST", "dstid" => "PDT"),
"PST8PDT" => array ("id" => "PST", "dstid" => "PDT"),
"Pacific/Pitcairn" => array ("id" => "PST"),
"SystemV/PST8" => array ("id" => "PST"),
"SystemV/PST8PDT" => array ("id" => "PST", "dstid" => "PDT"),
"US/Pacific" => array ("id" => "PST", "dstid" => "PDT"),
"US/Pacific-New" => array ("id" => "PST", "dstid" => "PDT"),
"America/Boise" => array ("id" => "MST", "dstid" => "MDT"),
"America/Cambridge_Bay" => array ("id" => "MST", "dstid" => "MDT"),
"America/Chihuahua" => array ("id" => "MST", "dstid" => "MDT"),
"America/Dawson_Creek" => array ("id" => "MST"),
"America/Denver" => array ("id" => "MST", "dstid" => "MDT"),
"America/Edmonton" => array ("id" => "MST", "dstid" => "MDT"),
"America/Hermosillo" => array ("id" => "MST"),
"America/Inuvik" => array ("id" => "MST", "dstid" => "MDT"),
"America/Mazatlan" => array ("id" => "MST", "dstid" => "MDT"),
"America/Phoenix" => array ("id" => "MST"),
"America/Shiprock" => array ("id" => "MST", "dstid" => "MDT"),
"America/Yellowknife" => array ("id" => "MST", "dstid" => "MDT"),
"Canada/Mountain" => array ("id" => "MST", "dstid" => "MDT"),
"Etc/GMT-7" => array ("id" => "GMT-0700"),
"MST" => array ("id" => "MST", "dstid" => "MDT"),
"MST7MDT" => array ("id" => "MST", "dstid" => "MDT"),
"Mexico/BajaSur" => array ("id" => "MST", "dstid" => "MDT"),
"Navajo" => array ("id" => "MST", "dstid" => "MDT"),
"PNT" => array ("id" => "MST"),
"SystemV/MST7" => array ("id" => "MST"),
"SystemV/MST7MDT" => array ("id" => "MST", "dstid" => "MDT"),
"US/Arizona" => array ("id" => "MST"),
"US/Mountain" => array ("id" => "MST", "dstid" => "MDT"),
"America/Belize" => array ("id" => "CST"),
"America/Cancun" => array ("id" => "CST", "dstid" => "CDT"),
"America/Chicago" => array ("id" => "CST", "dstid" => "CDT"),
"America/Costa_Rica" => array ("id" => "CST"),
"America/El_Salvador" => array ("id" => "CST"),
"America/Guatemala" => array ("id" => "CST"),
"America/Managua" => array ("id" => "CST"),
"America/Menominee" => array ("id" => "CST", "dstid" => "CDT"),
"America/Merida" => array ("id" => "CST", "dstid" => "CDT"),
"America/Mexico_City" => array ("id" => "CST"),
"America/Monterrey" => array ("id" => "CST", "dstid" => "CDT"),
"America/North_Dakota/Center" => array ("id" => "CST", "dstid" => "CDT"),
"America/Rainy_River" => array ("id" => "CST", "dstid" => "CDT"),
"America/Rankin_Inlet" => array ("id" => "EST", "dstid" => "EDT"),
"America/Regina" => array ("id" => "CST"),
"America/Swift_Current" => array ("id" => "CST"),
"America/Tegucigalpa" => array ("id" => "CST"),
"America/Winnipeg" => array ("id" => "CST", "dstid" => "CDT"),
"CST" => array ("id" => "CST", "dstid" => "CDT"),
"CST6CDT" => array ("id" => "CST", "dstid" => "CDT"),
"Canada/Central" => array ("id" => "CST", "dstid" => "CDT"),
"Canada/East-Saskatchewan" => array ("id" => "CST"),
"Canada/Saskatchewan" => array ("id" => "CST"),
"Chile/EasterIsland" => array ("id" => "EAST", "dstid" => "EASST"),
"Etc/GMT-6" => array ("id" => "GMT-0600"),
"Mexico/General" => array ("id" => "CST"),
"Pacific/Easter" => array ("id" => "EAST", "dstid" => "EASST"),
"Pacific/Galapagos" => array ("id" => "GALT"),
"SystemV/CST6" => array ("id" => "CST"),
"SystemV/CST6CDT" => array ("id" => "CST", "dstid" => "CDT"),
"US/Central" => array ("id" => "CST", "dstid" => "CDT"),
"America/Bogota" => array ("id" => "COT"),
"America/Cayman" => array ("id" => "EST"),
"America/Detroit" => array ("id" => "EST", "dstid" => "EDT"),
"America/Eirunepe" => array ("id" => "ACT"),
"America/Fort_Wayne" => array ("id" => "EST"),
"America/Grand_Turk" => array ("id" => "EST", "dstid" => "EDT"),
"America/Guayaquil" => array ("id" => "ECT"),
"America/Havana" => array ("id" => "CST", "dstid" => "CDT"),
"America/Indiana/Indianapolis" => array ("id" => "EST"),
"America/Indiana/Knox" => array ("id" => "EST"),
"America/Indiana/Marengo" => array ("id" => "EST"),
"America/Indiana/Vevay" => array ("id" => "EST"),
"America/Indianapolis" => array ("id" => "EST"),
"America/Iqaluit" => array ("id" => "EST", "dstid" => "EDT"),
"America/Jamaica" => array ("id" => "EST"),
"America/Kentucky/Louisville" => array ("id" => "EST", "dstid" => "EDT"),
"America/Kentucky/Monticello" => array ("id" => "EST", "dstid" => "EDT"),
"America/Knox_IN" => array ("id" => "EST"),
"America/Lima" => array ("id" => "PET"),
"America/Louisville" => array ("id" => "EST", "dstid" => "EDT"),
"America/Montreal" => array ("id" => "EST", "dstid" => "EDT"),
"America/Nassau" => array ("id" => "EST", "dstid" => "EDT"),
"America/New_York" => array ("id" => "EST", "dstid" => "EDT"),
"America/Nipigon" => array ("id" => "EST", "dstid" => "EDT"),
"America/Panama" => array ("id" => "EST"),
"America/Pangnirtung" => array ("id" => "EST", "dstid" => "EDT"),
"America/Port-au-Prince" => array ("id" => "EST"),
"America/Porto_Acre" => array ("id" => "ACT"),
"America/Rio_Branco" => array ("id" => "ACT"),
"America/Thunder_Bay" => array ("id" => "EST", "dstid" => "EDT"),
"Brazil/Acre" => array ("id" => "ACT"),
"Canada/Eastern" => array ("id" => "EST", "dstid" => "EDT"),
"Cuba" => array ("id" => "CST", "dstid" => "CDT"),
"EST" => array ("id" => "EST", "dstid" => "EDT"),
"EST5EDT" => array ("id" => "EST", "dstid" => "EDT"),
"Etc/GMT-5" => array ("id" => "GMT-0500"),
"IET" => array ("id" => "EST"),
"Jamaica" => array ("id" => "EST"),
"SystemV/EST5" => array ("id" => "EST"),
"SystemV/EST5EDT" => array ("id" => "EST", "dstid" => "EDT"),
"US/East-Indiana" => array ("id" => "EST"),
"US/Eastern" => array ("id" => "EST", "dstid" => "EDT"),
"US/Indiana-Starke" => array ("id" => "EST"),
"US/Michigan" => array ("id" => "EST", "dstid" => "EDT"),
"America/Anguilla" => array ("id" => "AST"),
"America/Antigua" => array ("id" => "AST"),
"America/Aruba" => array ("id" => "AST"),
"America/Asuncion" => array ("id" => "PYT", "dstid" => "PYST"),
"America/Barbados" => array ("id" => "AST"),
"America/Boa_Vista" => array ("id" => "AMT"),
"America/Caracas" => array ("id" => "VET"),
"America/Cuiaba" => array ("id" => "AMT", "dstid" => "AMST"),
"America/Curacao" => array ("id" => "AST"),
"America/Dominica" => array ("id" => "AST"),
"America/Glace_Bay" => array ("id" => "AST", "dstid" => "ADT"),
"America/Goose_Bay" => array ("id" => "AST", "dstid" => "ADT"),
"America/Grenada" => array ("id" => "AST"),
"America/Guadeloupe" => array ("id" => "AST"),
"America/Guyana" => array ("id" => "GYT"),
"America/Halifax" => array ("id" => "AST", "dstid" => "ADT"),
"America/La_Paz" => array ("id" => "BOT"),
"America/Manaus" => array ("id" => "AMT"),
"America/Martinique" => array ("id" => "AST"),
"America/Montserrat" => array ("id" => "AST"),
"America/Port_of_Spain" => array ("id" => "AST"),
"America/Porto_Velho" => array ("id" => "AMT"),
"America/Puerto_Rico" => array ("id" => "AST"),
"America/Santiago" => array ("id" => "CLT", "dstid" => "CLST"),
"America/Santo_Domingo" => array ("id" => "AST"),
"America/St_Kitts" => array ("id" => "AST"),
"America/St_Lucia" => array ("id" => "AST"),
"America/St_Thomas" => array ("id" => "AST"),
"America/St_Vincent" => array ("id" => "AST"),
"America/Thule" => array ("id" => "AST"),
"America/Tortola" => array ("id" => "AST"),
"America/Virgin" => array ("id" => "AST"),
"Antarctica/Palmer" => array ("id" => "CLT", "dstid" => "CLST"),
"Atlantic/Bermuda" => array ("id" => "AST", "dstid" => "ADT"),
"Atlantic/Stanley" => array ("id" => "FKT", "dstid" => "FKST"),
"Brazil/West" => array ("id" => "AMT"),
"Canada/Atlantic" => array ("id" => "AST", "dstid" => "ADT"),
"Chile/Continental" => array ("id" => "CLT", "dstid" => "CLST"),
"Etc/GMT-4" => array ("id" => "GMT-0400"),
"PRT" => array ("id" => "AST"),
"SystemV/AST4" => array ("id" => "AST"),
"SystemV/AST4ADT" => array ("id" => "AST", "dstid" => "ADT"),
"America/St_Johns" => array ("id" => "NST", "dstid" => "NDT"),
"CNT" => array ("id" => "NST", "dstid" => "NDT"),
"Canada/Newfoundland" => array ("id" => "NST", "dstid" => "NDT"),
"AGT" => array ("id" => "ART"),
"America/Araguaina" => array ("id" => "BRT", "dstid" => "BRST"),
"America/Belem" => array ("id" => "BRT"),
"America/Buenos_Aires" => array ("id" => "ART"),
"America/Catamarca" => array ("id" => "ART"),
"America/Cayenne" => array ("id" => "GFT"),
"America/Cordoba" => array ("id" => "ART"),
"America/Fortaleza" => array ("id" => "BRT", "dstid" => "BRST"),
"America/Godthab" => array ("id" => "WGT", "dstid" => "WGST"),
"America/Jujuy" => array ("id" => "ART"),
"America/Maceio" => array ("id" => "BRT", "dstid" => "BRST"),
"America/Mendoza" => array ("id" => "ART"),
"America/Miquelon" => array ("id" => "PMST", "dstid" => "PMDT"),
"America/Montevideo" => array ("id" => "UYT"),
"America/Paramaribo" => array ("id" => "SRT"),
"America/Recife" => array ("id" => "BRT", "dstid" => "BRST"),
"America/Rosario" => array ("id" => "ART"),
"America/Sao_Paulo" => array ("id" => "BRT", "dstid" => "BRST"),
"BET" => array ("id" => "BRT", "dstid" => "BRST"),
"Brazil/East" => array ("id" => "BRT", "dstid" => "BRST"),
"Etc/GMT-3" => array ("id" => "GMT-0300"),
"America/Noronha" => array ("id" => "FNT"),
"Atlantic/South_Georgia" => array ("id" => "GST"),
"Brazil/DeNoronha" => array ("id" => "FNT"),
"Etc/GMT-2" => array ("id" => "GMT-0200"),
"America/Scoresbysund" => array ("id" => "EGT", "dstid" => "EGST"),
"Atlantic/Azores" => array ("id" => "AZOT", "dstid" => "AZOST"),
"Atlantic/Cape_Verde" => array ("id" => "CVT"),
"Etc/GMT-1" => array ("id" => "GMT-0100"),
"Africa/Abidjan" => array ("id" => "GMT"),
"Africa/Accra" => array ("id" => "GMT"),
"Africa/Bamako" => array ("id" => "GMT"),
"Africa/Banjul" => array ("id" => "GMT"),
"Africa/Bissau" => array ("id" => "GMT"),
"Africa/Casablanca" => array ("id" => "WET"),
"Africa/Conakry" => array ("id" => "GMT"),
"Africa/Dakar" => array ("id" => "GMT"),
"Africa/El_Aaiun" => array ("id" => "WET"),
"Africa/Freetown" => array ("id" => "GMT"),
"Africa/Lome" => array ("id" => "GMT"),
"Africa/Monrovia" => array ("id" => "GMT"),
"Africa/Nouakchott" => array ("id" => "GMT"),
"Africa/Ouagadougou" => array ("id" => "GMT"),
"Africa/Sao_Tome" => array ("id" => "GMT"),
"Africa/Timbuktu" => array ("id" => "GMT"),
"America/Danmarkshavn" => array ("id" => "GMT"),
"Atlantic/Canary" => array ("id" => "WET", "dstid" => "WEST"),
"Atlantic/Faeroe" => array ("id" => "WET", "dstid" => "WEST"),
"Atlantic/Madeira" => array ("id" => "WET", "dstid" => "WEST"),
"Atlantic/Reykjavik" => array ("id" => "GMT"),
"Atlantic/St_Helena" => array ("id" => "GMT"),
"Eire" => array ("id" => "GMT", "dstid" => "IST"),
"Etc/GMT" => array ("id" => "GMT+0000"),
"Etc/GMT+0" => array ("id" => "GMT+0000"),
"Etc/GMT-0" => array ("id" => "GMT+0000"),
"Etc/GMT0" => array ("id" => "GMT+0000"),
"Etc/Greenwich" => array ("id" => "GMT"),
"Etc/UCT" => array ("id" => "UTC"),
"Etc/UTC" => array ("id" => "UTC"),
"Etc/Universal" => array ("id" => "UTC"),
"Etc/Zulu" => array ("id" => "UTC"),
"Europe/Belfast" => array ("id" => "GMT", "dstid" => "BST"),
"Europe/Dublin" => array ("id" => "GMT", "dstid" => "IST"),
"Europe/Lisbon" => array ("id" => "WET", "dstid" => "WEST"),
"Europe/London" => array ("id" => "GMT", "dstid" => "BST"),
"GB" => array ("id" => "GMT", "dstid" => "BST"),
"GB-Eire" => array ("id" => "GMT", "dstid" => "BST"),
"GMT" => array ("id" => "GMT"),
"GMT0" => array ("id" => "GMT+0000"),
"Greenwich" => array ("id" => "GMT"),
"Iceland" => array ("id" => "GMT"),
"Portugal" => array ("id" => "WET", "dstid" => "WEST"),
"UCT" => array ("id" => "UTC"),
"UTC" => array ("id" => "UTC"),
"Universal" => array ("id" => "UTC"),
"WET" => array ("id" => "WET", "dstid" => "WEST"),
"Zulu" => array ("id" => "UTC"),
"Africa/Algiers" => array ("id" => "CET"),
"Africa/Bangui" => array ("id" => "WAT"),
"Africa/Brazzaville" => array ("id" => "WAT"),
"Africa/Ceuta" => array ("id" => "CET", "dstid" => "CEST"),
"Africa/Douala" => array ("id" => "WAT"),
"Africa/Kinshasa" => array ("id" => "WAT"),
"Africa/Lagos" => array ("id" => "WAT"),
"Africa/Libreville" => array ("id" => "WAT"),
"Africa/Luanda" => array ("id" => "WAT"),
"Africa/Malabo" => array ("id" => "WAT"),
"Africa/Ndjamena" => array ("id" => "WAT"),
"Africa/Niamey" => array ("id" => "WAT"),
"Africa/Porto-Novo" => array ("id" => "WAT"),
"Africa/Tunis" => array ("id" => "CET"),
"Africa/Windhoek" => array ("id" => "WAT", "dstid" => "WAST"),
"Arctic/Longyearbyen" => array ("id" => "CET", "dstid" => "CEST"),
"Atlantic/Jan_Mayen" => array ("id" => "EGT", "dstid" => "EGST"),
"CET" => array ("id" => "CET", "dstid" => "CEST"),
"ECT" => array ("id" => "CET", "dstid" => "CEST"),
"Etc/GMT+1" => array ("id" => "GMT+0100"),
"Europe/Amsterdam" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Andorra" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Belgrade" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Berlin" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Bratislava" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Brussels" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Budapest" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Copenhagen" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Gibraltar" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Ljubljana" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Luxembourg" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Madrid" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Malta" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Monaco" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Oslo" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Paris" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Prague" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Rome" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/San_Marino" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Sarajevo" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Skopje" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Stockholm" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Tirane" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Vaduz" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Vatican" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Vienna" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Warsaw" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Zagreb" => array ("id" => "CET", "dstid" => "CEST"),
"Europe/Zurich" => array ("id" => "CET", "dstid" => "CEST"),
"MET" => array ("id" => "MET", "dstid" => "MEST"),
"Poland" => array ("id" => "CET", "dstid" => "CEST"),
"ART" => array ("id" => "EET", "dstid" => "EEST"),
"Africa/Blantyre" => array ("id" => "CAT"),
"Africa/Bujumbura" => array ("id" => "CAT"),
"Africa/Cairo" => array ("id" => "EET", "dstid" => "EEST"),
"Africa/Gaborone" => array ("id" => "CAT"),
"Africa/Harare" => array ("id" => "CAT"),
"Africa/Johannesburg" => array ("id" => "SAST"),
"Africa/Kigali" => array ("id" => "CAT"),
"Africa/Lubumbashi" => array ("id" => "CAT"),
"Africa/Lusaka" => array ("id" => "CAT"),
"Africa/Maputo" => array ("id" => "CAT"),
"Africa/Maseru" => array ("id" => "SAST"),
"Africa/Mbabane" => array ("id" => "SAST"),
"Africa/Tripoli" => array ("id" => "EET"),
"Asia/Amman" => array ("id" => "EET", "dstid" => "EEST"),
"Asia/Beirut" => array ("id" => "EET", "dstid" => "EEST"),
"Asia/Damascus" => array ("id" => "EET", "dstid" => "EEST"),
"Asia/Gaza" => array ("id" => "EET", "dstid" => "EEST"),
"Asia/Istanbul" => array ("id" => "EET", "dstid" => "EEST"),
"Asia/Jerusalem" => array ("id" => "IST", "dstid" => "IDT"),
"Asia/Nicosia" => array ("id" => "EET", "dstid" => "EEST"),
"Asia/Tel_Aviv" => array ("id" => "IST", "dstid" => "IDT"),
"CAT" => array ("id" => "CAT"),
"EET" => array ("id" => "EET", "dstid" => "EEST"),
"Egypt" => array ("id" => "EET", "dstid" => "EEST"),
"Etc/GMT+2" => array ("id" => "GMT+0200"),
"Europe/Athens" => array ("id" => "EET", "dstid" => "EEST"),
"Europe/Bucharest" => array ("id" => "EET", "dstid" => "EEST"),
"Europe/Chisinau" => array ("id" => "EET", "dstid" => "EEST"),
"Europe/Helsinki" => array ("id" => "EET", "dstid" => "EEST"),
"Europe/Istanbul" => array ("id" => "EET", "dstid" => "EEST"),
"Europe/Kaliningrad" => array ("id" => "EET", "dstid" => "EEST"),
"Europe/Kiev" => array ("id" => "EET", "dstid" => "EEST"),
"Europe/Minsk" => array ("id" => "EET", "dstid" => "EEST"),
"Europe/Nicosia" => array ("id" => "EET", "dstid" => "EEST"),
"Europe/Riga" => array ("id" => "EET", "dstid" => "EEST"),
"Europe/Simferopol" => array ("id" => "EET", "dstid" => "EEST"),
"Europe/Sofia" => array ("id" => "EET", "dstid" => "EEST"),
"Europe/Tallinn" => array ("id" => "EET"),
"Europe/Tiraspol" => array ("id" => "EET", "dstid" => "EEST"),
"Europe/Uzhgorod" => array ("id" => "EET", "dstid" => "EEST"),
"Europe/Vilnius" => array ("id" => "EET"),
"Europe/Zaporozhye" => array ("id" => "EET", "dstid" => "EEST"),
"Israel" => array ("id" => "IST", "dstid" => "IDT"),
"Libya" => array ("id" => "EET"),
"Turkey" => array ("id" => "EET", "dstid" => "EEST"),
"Africa/Addis_Ababa" => array ("id" => "EAT"),
"Africa/Asmera" => array ("id" => "EAT"),
"Africa/Dar_es_Salaam" => array ("id" => "EAT"),
"Africa/Djibouti" => array ("id" => "EAT"),
"Africa/Kampala" => array ("id" => "EAT"),
"Africa/Khartoum" => array ("id" => "EAT"),
"Africa/Mogadishu" => array ("id" => "EAT"),
"Africa/Nairobi" => array ("id" => "EAT"),
"Antarctica/Syowa" => array ("id" => "SYOT"),
"Asia/Aden" => array ("id" => "AST"),
"Asia/Baghdad" => array ("id" => "AST", "dstid" => "ADT"),
"Asia/Bahrain" => array ("id" => "AST"),
"Asia/Kuwait" => array ("id" => "AST"),
"Asia/Qatar" => array ("id" => "AST"),
"Asia/Riyadh" => array ("id" => "AST"),
"EAT" => array ("id" => "EAT"),
"Etc/GMT+3" => array ("id" => "GMT+0300"),
"Europe/Moscow" => array ("id" => "MSK", "dstid" => "MSD"),
"Indian/Antananarivo" => array ("id" => "EAT"),
"Indian/Comoro" => array ("id" => "EAT"),
"Indian/Mayotte" => array ("id" => "EAT"),
"W-SU" => array ("id" => "MSK", "dstid" => "MSD"),
"Asia/Riyadh87" => array ("id" => "GMT+03:07"),
"Asia/Riyadh88" => array ("id" => "GMT+03:07"),
"Asia/Riyadh89" => array ("id" => "GMT+03:07"),
"Mideast/Riyadh87" => array ("id" => "GMT+03:07"),
"Mideast/Riyadh88" => array ("id" => "GMT+03:07"),
"Mideast/Riyadh89" => array ("id" => "GMT+03:07"),
"Asia/Tehran" => array ("id" => "IRT", "dstid" => "IRST"),
"Iran" => array ("id" => "IRT", "dstid" => "IRST"),
"Asia/Aqtau" => array ("id" => "AQTT", "dstid" => "AQTST"),
"Asia/Baku" => array ("id" => "AZT", "dstid" => "AZST"),
"Asia/Dubai" => array ("id" => "GST"),
"Asia/Muscat" => array ("id" => "GST"),
"Asia/Tbilisi" => array ("id" => "GET", "dstid" => "GEST"),
"Asia/Yerevan" => array ("id" => "AMT", "dstid" => "AMST"),
"Etc/GMT+4" => array ("id" => "GMT+0400"),
"Europe/Samara" => array ("id" => "SAMT", "dstid" => "SAMST"),
"Indian/Mahe" => array ("id" => "SCT"),
"Indian/Mauritius" => array ("id" => "MUT"),
"Indian/Reunion" => array ("id" => "RET"),
"NET" => array ("id" => "AMT", "dstid" => "AMST"),
"Asia/Kabul" => array ("id" => "AFT"),
"Asia/Aqtobe" => array ("id" => "AQTT", "dstid" => "AQTST"),
"Asia/Ashgabat" => array ("id" => "TMT"),
"Asia/Ashkhabad" => array ("id" => "TMT"),
"Asia/Bishkek" => array ("id" => "KGT", "dstid" => "KGST"),
"Asia/Dushanbe" => array ("id" => "TJT"),
"Asia/Karachi" => array ("id" => "PKT"),
"Asia/Samarkand" => array ("id" => "TMT"),
"Asia/Tashkent" => array ("id" => "UZT"),
"Asia/Yekaterinburg" => array ("id" => "YEKT", "dstid" => "YEKST"),
"Etc/GMT+5" => array ("id" => "GMT+0500"),
"Indian/Kerguelen" => array ("id" => "TFT"),
"Indian/Maldives" => array ("id" => "MVT"),
"PLT" => array ("id" => "PKT"),
"Asia/Calcutta" => array ("id" => "IST"),
"IST" => array ("id" => "IST"),
"Asia/Katmandu" => array ("id" => "NPT"),
"Antarctica/Mawson" => array ("id" => "MAWT"),
"Antarctica/Vostok" => array ("id" => "VOST"),
"Asia/Almaty" => array ("id" => "ALMT", "dstid" => "ALMST"),
"Asia/Colombo" => array ("id" => "LKT"),
"Asia/Dacca" => array ("id" => "BDT"),
"Asia/Dhaka" => array ("id" => "BDT"),
"Asia/Novosibirsk" => array ("id" => "NOVT", "dstid" => "NOVST"),
"Asia/Omsk" => array ("id" => "OMST", "dstid" => "OMSST"),
"Asia/Thimbu" => array ("id" => "BTT"),
"Asia/Thimphu" => array ("id" => "BTT"),
"BST" => array ("id" => "BDT"),
"Etc/GMT+6" => array ("id" => "GMT+0600"),
"Indian/Chagos" => array ("id" => "IOT"),
"Asia/Rangoon" => array ("id" => "MMT"),
"Indian/Cocos" => array ("id" => "CCT"),
"Antarctica/Davis" => array ("id" => "DAVT"),
"Asia/Bangkok" => array ("id" => "ICT"),
"Asia/Hovd" => array ("id" => "HOVT"),
"Asia/Jakarta" => array ("id" => "WIT"),
"Asia/Krasnoyarsk" => array ("id" => "KRAT", "dstid" => "KRAST"),
"Asia/Phnom_Penh" => array ("id" => "ICT"),
"Asia/Pontianak" => array ("id" => "WIT"),
"Asia/Saigon" => array ("id" => "ICT"),
"Asia/Vientiane" => array ("id" => "ICT"),
"Etc/GMT+7" => array ("id" => "GMT+0700"),
"Indian/Christmas" => array ("id" => "CXT"),
"VST" => array ("id" => "ICT"),
"Antarctica/Casey" => array ("id" => "WST"),
"Asia/Brunei" => array ("id" => "BNT"),
"Asia/Chongqing" => array ("id" => "CST"),
"Asia/Chungking" => array ("id" => "CST"),
"Asia/Harbin" => array ("id" => "CST"),
"Asia/Hong_Kong" => array ("id" => "HKT"),
"Asia/Irkutsk" => array ("id" => "IRKT", "dstid" => "IRKST"),
"Asia/Kashgar" => array ("id" => "CST"),
"Asia/Kuala_Lumpur" => array ("id" => "MYT"),
"Asia/Kuching" => array ("id" => "MYT"),
"Asia/Macao" => array ("id" => "CST"),
"Asia/Manila" => array ("id" => "PHT"),
"Asia/Shanghai" => array ("id" => "CST"),
"Asia/Singapore" => array ("id" => "SGT"),
"Asia/Taipei" => array ("id" => "CST"),
"Asia/Ujung_Pandang" => array ("id" => "CIT"),
"Asia/Ulaanbaatar" => array ("id" => "ULAT"),
"Asia/Ulan_Bator" => array ("id" => "ULAT"),
"Asia/Urumqi" => array ("id" => "CST"),
"Australia/Perth" => array ("id" => "WST"),
"Australia/West" => array ("id" => "WST"),
"CTT" => array ("id" => "CST"),
"Etc/GMT+8" => array ("id" => "GMT+0800"),
"Hongkong" => array ("id" => "HKT"),
"PRC" => array ("id" => "CST"),
"Singapore" => array ("id" => "SGT"),
"Asia/Choibalsan" => array ("id" => "CHOT"),
"Asia/Dili" => array ("id" => "TPT"),
"Asia/Jayapura" => array ("id" => "EIT"),
"Asia/Pyongyang" => array ("id" => "KST"),
"Asia/Seoul" => array ("id" => "KST"),
"Asia/Tokyo" => array ("id" => "JST"),
"Asia/Yakutsk" => array ("id" => "YAKT", "dstid" => "YAKST"),
"Etc/GMT+9" => array ("id" => "GMT+0900"),
"JST" => array ("id" => "JST"),
"Japan" => array ("id" => "JST"),
"Pacific/Palau" => array ("id" => "PWT"),
"ROK" => array ("id" => "KST"),
"ACT" => array ("id" => "CST"),
"Australia/Adelaide" => array ("id" => "CST", "dstid" => "CST"),
"Australia/Broken_Hill" => array ("id" => "CST", "dstid" => "CST"),
"Australia/Darwin" => array ("id" => "CST"),
"Australia/North" => array ("id" => "CST"),
"Australia/South" => array ("id" => "CST", "dstid" => "CST"),
"Australia/Yancowinna" => array ("id" => "CST", "dstid" => "CST"),
"AET" => array ("id" => "EST", "dstid" => "EST"),
"Antarctica/DumontDUrville" => array ("id" => "DDUT"),
"Asia/Sakhalin" => array ("id" => "SAKT", "dstid" => "SAKST"),
"Asia/Vladivostok" => array ("id" => "VLAT", "dstid" => "VLAST"),
"Australia/ACT" => array ("id" => "EST", "dstid" => "EST"),
"Australia/Brisbane" => array ("id" => "EST"),
"Australia/Canberra" => array ("id" => "EST", "dstid" => "EST"),
"Australia/Hobart" => array ("id" => "EST", "dstid" => "EST"),
"Australia/Lindeman" => array ("id" => "EST"),
"Australia/Melbourne" => array ("id" => "EST", "dstid" => "EST"),
"Australia/NSW" => array ("id" => "EST", "dstid" => "EST"),
"Australia/Queensland" => array ("id" => "EST"),
"Australia/Sydney" => array ("id" => "EST", "dstid" => "EST"),
"Australia/Tasmania" => array ("id" => "EST", "dstid" => "EST"),
"Australia/Victoria" => array ("id" => "EST", "dstid" => "EST"),
"Etc/GMT+10" => array ("id" => "GMT+1000"),
"Pacific/Guam" => array ("id" => "ChST"),
"Pacific/Port_Moresby" => array ("id" => "PGT"),
"Pacific/Saipan" => array ("id" => "ChST"),
"Pacific/Truk" => array ("id" => "TRUT"),
"Pacific/Yap" => array ("id" => "YAPT"),
"Australia/LHI" => array ("id" => "LHST", "dstid" => "LHST"),
"Australia/Lord_Howe" => array ("id" => "LHST", "dstid" => "LHST"),
"Asia/Magadan" => array ("id" => "MAGT", "dstid" => "MAGST"),
"Etc/GMT+11" => array ("id" => "GMT+1100"),
"Pacific/Efate" => array ("id" => "VUT"),
"Pacific/Guadalcanal" => array ("id" => "SBT"),
"Pacific/Kosrae" => array ("id" => "KOST"),
"Pacific/Noumea" => array ("id" => "NCT"),
"Pacific/Ponape" => array ("id" => "PONT"),
"SST" => array ("id" => "SBT"),
"Pacific/Norfolk" => array ("id" => "NFT"),
"Antarctica/McMurdo" => array ("id" => "NZST", "dstid" => "NZDT"),
"Antarctica/South_Pole" => array ("id" => "NZST", "dstid" => "NZDT"),
"Asia/Anadyr" => array ("id" => "ANAT", "dstid" => "ANAST"),
"Asia/Kamchatka" => array ("id" => "PETT", "dstid" => "PETST"),
"Etc/GMT+12" => array ("id" => "GMT+1200"),
"Kwajalein" => array ("id" => "MHT"),
"NST" => array ("id" => "NZST", "dstid" => "NZDT"),
"NZ" => array ("id" => "NZST", "dstid" => "NZDT"),
"Pacific/Auckland" => array ("id" => "NZST", "dstid" => "NZDT"),
"Pacific/Fiji" => array ("id" => "FJT"),
"Pacific/Funafuti" => array ("id" => "TVT"),
"Pacific/Kwajalein" => array ("id" => "MHT"),
"Pacific/Majuro" => array ("id" => "MHT"),
"Pacific/Nauru" => array ("id" => "NRT"),
"Pacific/Tarawa" => array ("id" => "GILT"),
"Pacific/Wake" => array ("id" => "WAKT"),
"Pacific/Wallis" => array ("id" => "WFT"),
"NZ-CHAT" => array ("id" => "CHAST", "dstid" => "CHADT"),
"Pacific/Chatham" => array ("id" => "CHAST", "dstid" => "CHADT"),
"Etc/GMT+13" => array ("id" => "GMT+1300"),
"Pacific/Enderbury" => array ("id" => "PHOT"),
"Pacific/Tongatapu" => array ("id" => "TOT"),
"Etc/GMT+14" => array ("id" => "GMT+1400"),
"Pacific/Kiritimati" => array ("id" => "LINT")
);


?>